#
# Module manifest for module 'learnExport'
#
# Generated by: Renaud Wangler
#
# Generated on: 02/09/2026
#

@{
RootModule = 'learnExport.psm1'
ModuleVersion = '0.1.0'
# ID used to uniquely identify this module
GUID = '8d41dc31-5591-4bec-8dbf-991d4ba6f1de'
Author      = 'Renaud Wangler'
Description = 'Export Microsoft Learn courses to Markdown, EPUB and PDF.'
CompanyName = 'ib Cegos'
ProjectUri = 'https://github.com/renaudwangler/ib'
IconUri = 'https://raw.githubusercontent.com/renaudwangler/ib/master/extra/logo-ib.png'
Tags = @(
'MicrosoftLearn'
'Training'
'EPUB'
'PDF'
'Pandoc')
Copyright = '(c) Renaud Wangler. All rights reserved.'
FunctionsToExport = @( 'Export-ibCourse' )
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'
PrivateData = @{
    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        # Tags = @()
        # A URL to the license for this module.
        # LicenseUri = ''
        # A URL to the main website for this project.
        # ProjectUri = ''
        # A URL to an icon representing this module.
        # IconUri = ''
        # ReleaseNotes of this module
        # ReleaseNotes = ''
        # Prerelease string of this module
        # Prerelease = ''
        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false
        # External dependent modules of this module
        # ExternalModuleDependencies = @()
    }
}
# HelpInfo URI of this module
# HelpInfoURI = ''
# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = 'ib'
}

