name: Publish PowerShell Module

on:
  workflow_dispatch:

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.PSGALLERY_NUGET_KEY }}
        shell: pwsh
        run: |
          $moduleVersion=(import-powershellDataFile -Path ./ib2/ib2.psd1).ModuleVersion
           if ((Find-Module ib2).version -ne $moduleVersion) {
              #Nouvelle version : lancer la publication
              update-ModuleManifest -Path ./ib2/ib2.psd1 -ModuleVersion $moduleVersion
              Publish-Module -Path ./ib2 -NuGetApiKey $env:NUGET_KEY -Verbose}
