name: Publish learnExport Module

on:
  push:
    branches:
      - master
    paths:
      - 'learnExport/**'


jobs:
  publish-to-gallery:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.PSGALLERY_NUGET_KEY }}
        shell: pwsh
        run: |
          $moduleVersion=(Import-powershellDataFile -Path ./learnExport/learnExport.psd1).ModuleVersion
          $PSDefaultParameterValues['*:Encoding']='utf8BOM'
          $PublishedModule = Find-Module learnExport -ErrorAction SilentlyContinue
          if(-not $PublishedModule -or [version]$PublishedModule.Version -lt [version]$moduleVersion) {
              #Nouvelle version : lancer la publication
              Publish-Module -Path ./learnExport -NuGetApiKey $env:NUGET_KEY -Verbose
              write-host "::notice title=Publication réussie::Publication de la version $moduleVersion vers la gallerie Powershell"}
          else {write-host "::warning title=Version identique::La version n'a pas changé, pas de publication"}
